# Generated by Django 5.1.6 on 2025-03-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreasTecnologicas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_tecnologica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=100)),
                ('dt_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Financiadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('financiador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projeto', models.CharField(max_length=100)),
                ('coordenador', models.CharField(max_length=100)),
                ('ativo', models.BooleanField()),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField()),
                ('valor', models.FloatField(verbose_name=2)),
                ('qtd_membros', models.IntegerField()),
                ('equipe', models.ManyToManyField(to='api.colaboradores')),
                ('id_area_tecnologica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.areastecnologicas')),
                ('id_financiador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.financiadores')),
            ],
        ),
    ]
