# Generated by Django 5.1.6 on 2025-03-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='id_area_tecnologica',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='id_financiador',
        ),
        migrations.RenameField(
            model_name='financiadores',
            old_name='id',
            new_name='id_financiador',
        ),
        migrations.DeleteModel(
            name='AreasTecnologicas',
        ),
        migrations.DeleteModel(
            name='Colaboradores',
        ),
        migrations.DeleteModel(
            name='Projetos',
        ),
    ]
