# Generated by Django 5.1.6 on 2025-03-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_projetos_id_area_tecnologica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=100)),
                ('dt_nascimento', models.DateField()),
            ],
        ),
    ]
