# Generated by Django 5.1.6 on 2025-03-01 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_colaboradores'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasTecnologicas',
            fields=[
                ('id_area_tecnologica', models.AutoField(primary_key=True, serialize=False)),
                ('area_tecnologica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id_projeto', models.AutoField(primary_key=True, serialize=False)),
                ('projeto', models.CharField(max_length=100)),
                ('coordenador', models.CharField(max_length=100)),
                ('ativo', models.BooleanField()),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField()),
                ('valor', models.FloatField(verbose_name=2)),
                ('qtd_membros', models.IntegerField()),
                ('equipe', models.ManyToManyField(to='api.colaboradores')),
                ('id_area_tecnologica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.areastecnologicas')),
                ('id_financiador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.financiadores')),
            ],
        ),
    ]
