# Generated by Django 5.1.6 on 2025-03-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_areastecnologicas_projetos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='qtd_membros',
            field=models.IntegerField(editable=False),
        ),
    ]
