# Generated by Django 5.1.6 on 2025-03-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_projetos_qtd_membros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
